// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Script Commands
 * Place the definition of custom script commands in this file.
 * Format:
 *	BUILDIN_DEF(command_name,"parameters"),
 **/

//BUILDIN_DEF(example,""),
BUILDIN_DEF(premiumcardloot,"ii"),
BUILDIN_DEF(callblackmarketshop,"sii"),
BUILDIN_DEF(blackmarketprice,"i"),
BUILDIN_DEF(blackmarketenhance,"isrrr"),
BUILDIN_DEF(replaceequipped,"isiiiirrr"),
BUILDIN_DEF(sve_load,""),
BUILDIN_DEF(sve_mode,"i"),
BUILDIN_DEF(sve_stepcount,"i"),
BUILDIN_DEF(sve_stepcard,"ii"),
BUILDIN_DEF(sve_findstep,"ii"),
BUILDIN_DEF(sve_poolcount,"ii"),
BUILDIN_DEF(sve_poolitem,"iii"),
BUILDIN_DEF(sve_rollcharm,"ii"),
BUILDIN_DEF(sve_rogroupcount,"i"),
BUILDIN_DEF(sve_rollro,"ii"),
BUILDIN_DEF(svu_load,""),
BUILDIN_DEF(svu_slotcount,"i"),
BUILDIN_DEF(svu_slotcard,"ii"),
BUILDIN_DEF(svu_levelcount,"ii"),
BUILDIN_DEF(svu_levelitem,"iii"),
BUILDIN_DEF(svu_findlevel,"iii"),
BUILDIN_DEF(svu_roll,"ii"),
